"""
Watchlist for the Indian Daily Stock Scanner.

Symbols use the Yahoo Finance format (NSE ticker + ".NS").
A symbol that fails to download is simply skipped at scan time, so a stale
entry here never breaks the run.

Groups:
  NIFTY50  -> NIFTY 50 index constituents
  NEXT50   -> NIFTY Next 50 constituents (liquid subset)
  EXTRA    -> other large / highly liquid stocks worth watching
"""

NIFTY50 = [
    ("RELIANCE.NS", "Reliance Industries"),
    ("TCS.NS", "Tata Consultancy Services"),
    ("HDFCBANK.NS", "HDFC Bank"),
    ("ICICIBANK.NS", "ICICI Bank"),
    ("INFY.NS", "Infosys"),
    ("HINDUNILVR.NS", "Hindustan Unilever"),
    ("ITC.NS", "ITC"),
    ("SBIN.NS", "State Bank of India"),
    ("BHARTIARTL.NS", "Bharti Airtel"),
    ("KOTAKBANK.NS", "Kotak Mahindra Bank"),
    ("LT.NS", "Larsen & Toubro"),
    ("AXISBANK.NS", "Axis Bank"),
    ("BAJFINANCE.NS", "Bajaj Finance"),
    ("MARUTI.NS", "Maruti Suzuki"),
    ("SUNPHARMA.NS", "Sun Pharmaceutical"),
    ("TITAN.NS", "Titan Company"),
    ("ULTRACEMCO.NS", "UltraTech Cement"),
    ("HCLTECH.NS", "HCL Technologies"),
    ("ASIANPAINT.NS", "Asian Paints"),
    ("WIPRO.NS", "Wipro"),
    ("ADANIENT.NS", "Adani Enterprises"),
    ("ADANIPORTS.NS", "Adani Ports & SEZ"),
    ("APOLLOHOSP.NS", "Apollo Hospitals"),
    ("BAJAJ-AUTO.NS", "Bajaj Auto"),
    ("BAJAJFINSV.NS", "Bajaj Finserv"),
    ("BPCL.NS", "Bharat Petroleum"),
    ("CIPLA.NS", "Cipla"),
    ("COALINDIA.NS", "Coal India"),
    ("DRREDDY.NS", "Dr. Reddy's Laboratories"),
    ("EICHERMOT.NS", "Eicher Motors"),
    ("GRASIM.NS", "Grasim Industries"),
    ("HDFCLIFE.NS", "HDFC Life Insurance"),
    ("HEROMOTOCO.NS", "Hero MotoCorp"),
    ("HINDALCO.NS", "Hindalco Industries"),
    ("INDUSINDBK.NS", "IndusInd Bank"),
    ("JSWSTEEL.NS", "JSW Steel"),
    ("M&M.NS", "Mahindra & Mahindra"),
    ("NESTLEIND.NS", "Nestle India"),
    ("NTPC.NS", "NTPC"),
    ("ONGC.NS", "Oil & Natural Gas Corp"),
    ("POWERGRID.NS", "Power Grid Corp"),
    ("SBILIFE.NS", "SBI Life Insurance"),
    ("SHRIRAMFIN.NS", "Shriram Finance"),
    ("TMPV.NS", "Tata Motors Passenger Vehicles"),
    ("TMCV.NS", "Tata Motors Commercial Vehicles"),
    ("TECHM.NS", "Tech Mahindra"),
    ("TATACONSUM.NS", "Tata Consumer Products"),
    ("TRENT.NS", "Trent"),
    ("JIOFIN.NS", "Jio Financial Services"),
    ("DMART.NS", "Avenue Supermarts"),
]

NEXT50 = [
    ("BEL.NS", "Bharat Electronics"),
    ("HAL.NS", "Hindustan Aeronautics"),
    ("AMBUJACEM.NS", "Ambuja Cements"),
    ("ACC.NS", "ACC"),
    ("BHEL.NS", "BHEL"),
    ("BHARATFORG.NS", "Bharat Forge"),
    ("BOSCHLTD.NS", "Bosch"),
    ("CANBK.NS", "Canara Bank"),
    ("CHOLAFIN.NS", "Cholamandalam Finance"),
    ("DABUR.NS", "Dabur India"),
    ("DIVISLAB.NS", "Divi's Laboratories"),
    ("DLF.NS", "DLF"),
    ("GAIL.NS", "GAIL (India)"),
    ("GODREJCP.NS", "Godrej Consumer Products"),
    ("HDFCAMC.NS", "HDFC AMC"),
    ("ICICIGI.NS", "ICICI Lombard"),
    ("ICICIPRULI.NS", "ICICI Prudential Life"),
    ("IDFCFIRSTB.NS", "IDFC First Bank"),
    ("INDHOTEL.NS", "Indian Hotels"),
    ("IOC.NS", "Indian Oil Corp"),
    ("IRCTC.NS", "IRCTC"),
    ("JINDALSTEL.NS", "Jindal Steel & Power"),
    ("LICHSGFIN.NS", "LIC Housing Finance"),
    ("LUPIN.NS", "Lupin"),
    ("MUTHOOTFIN.NS", "Muthoot Finance"),
    ("NAVINFLUOR.NS", "Navin Fluorine"),
    ("PIDILITIND.NS", "Pidilite Industries"),
    ("PNB.NS", "Punjab National Bank"),
    ("PFC.NS", "Power Finance Corp"),
    ("RECLTD.NS", "REC"),
    ("SIEMENS.NS", "Siemens"),
    ("TATAPOWER.NS", "Tata Power"),
    ("TORNTPHARM.NS", "Torrent Pharmaceuticals"),
    ("VEDL.NS", "Vedanta"),
    ("ETERNAL.NS", "Eternal (Zomato)"),
    ("BRITANNIA.NS", "Britannia Industries"),
    ("COLPAL.NS", "Colgate-Palmolive India"),
    ("CONCOR.NS", "Container Corp of India"),
    ("HAVELLS.NS", "Havells India"),
    ("POLYCAB.NS", "Polycab India"),
    ("DIXON.NS", "Dixon Technologies"),
    ("PERSISTENT.NS", "Persistent Systems"),
    ("AUROPHARMA.NS", "Aurobindo Pharma"),
    ("MPHASIS.NS", "Mphasis"),
    ("TATAELXSI.NS", "Tata Elxsi"),
    ("BANKBARODA.NS", "Bank of Baroda"),
    ("UNIONBANK.NS", "Union Bank of India"),
    ("INDIANB.NS", "Indian Bank"),
    ("NHPC.NS", "NHPC"),
]

EXTRA = [
    ("PAYTM.NS", "One97 Communications (Paytm)"),
    ("ASHOKLEY.NS", "Ashok Leyland"),
    ("ABB.NS", "ABB India"),
    ("CROMPTON.NS", "Crompton Greaves"),
    ("VOLTAS.NS", "Voltas"),
    ("KALYANKJIL.NS", "Kalyan Jewellers"),
    ("UNITDSPR.NS", "United Spirits"),
    ("VBL.NS", "Varun Beverages"),
    ("MARICO.NS", "Marico"),
    ("PAGEIND.NS", "Page Industries"),
    ("BATAINDIA.NS", "Bata India"),
    ("COROMANDEL.NS", "Coromandel International"),
    ("DEEPAKNTR.NS", "Deepak Nitrite"),
    ("AARTIIND.NS", "Aarti Industries"),
    ("PIIND.NS", "PI Industries"),
    ("ESCORTS.NS", "Escorts Kubota"),
    ("CUMMINSIND.NS", "Cummins India"),
    ("THERMAX.NS", "Thermax"),
    ("BEML.NS", "BEML"),
    ("RAILTEL.NS", "RailTel Corp"),
    ("SUZLON.NS", "Suzlon Energy"),
    ("YESBANK.NS", "Yes Bank"),
    ("ZYDUSLIFE.NS", "Zydus Lifesciences"),
    ("ALKEM.NS", "Alkem Laboratories"),
    ("LAURUSLABS.NS", "Laurus Labs"),
    ("MAXHEALTH.NS", "Max Healthcare"),
    ("FORTIS.NS", "Fortis Healthcare"),
    ("SRF.NS", "SRF"),
    ("UPL.NS", "UPL"),
    ("BERGEPAINT.NS", "Berger Paints"),
    ("KEI.NS", "KEI Industries"),
    ("COFORGE.NS", "Coforge"),
    ("OFSS.NS", "Oracle Financial Services"),
    ("SJVN.NS", "SJVN"),
    ("RVNL.NS", "RVNL"),
    ("IRFC.NS", "IRFC"),
    ("ASTRAL.NS", "Astral"),
    ("INDIGO.NS", "InterGlobe Aviation"),
    ("BAJAJHLDNG.NS", "Bajaj Holdings"),
    ("GODREJPROP.NS", "Godrej Properties"),
    ("OBEROIRLTY.NS", "Oberoi Realty"),
    ("PRESTIGE.NS", "Prestige Estates"),
    ("LODHA.NS", "Macrotech Developers"),
    ("SUNTV.NS", "Sun TV Network"),
    ("TVSMOTOR.NS", "TVS Motor"),
    ("EXIDEIND.NS", "Exide Industries"),
    ("ARE&M.NS", "Amara Raja Energy & Mobility"),
    ("APOLLOTYRE.NS", "Apollo Tyres"),
    ("MRF.NS", "MRF"),
]

WATCHLIST = NIFTY50 + NEXT50 + EXTRA

# Symbol used to read the broad market trend (NIFTY 50 index)
MARKET_INDEX = "^NSEI"
MARKET_INDEX_NAME = "NIFTY 50 Index"

# India VIX - the market's "fear gauge" (calm <15, normal 15-20, nervous >20)
MARKET_VIX = "^INDIAVIX"
